/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AudioPlayer: typeof import('./src/components/AudioPlayer.vue')['default']
    Badge: typeof import('primevue/badge')['default']
    Button: typeof import('primevue/button')['default']
    Column: typeof import('primevue/column')['default']
    DataTable: typeof import('primevue/datatable')['default']
    Help: typeof import('./src/components/tabs/Help.vue')['default']
    InlineMessage: typeof import('primevue/inlinemessage')['default']
    MissionDetails: typeof import('./src/components/tabs/rally/MissionDetails.vue')['default']
    Password: typeof import('primevue/password')['default']
    ProgressBar: typeof import('primevue/progressbar')['default']
    ProgressSpinner: typeof import('primevue/progressspinner')['default']
    Rally: typeof import('./src/components/tabs/Rally.vue')['default']
    Settings: typeof import('./src/components/tabs/Settings.vue')['default']
    Tab: typeof import('primevue/tab')['default']
    TabList: typeof import('primevue/tablist')['default']
    TabPanel: typeof import('primevue/tabpanel')['default']
    TabPanels: typeof import('primevue/tabpanels')['default']
    Tabs: typeof import('primevue/tabs')['default']
    TopLevelNav: typeof import('./src/components/TopLevelNav.vue')['default']
    Tree: typeof import('primevue/tree')['default']
    Voices: typeof import('./src/components/tabs/Voices.vue')['default']
  }
  export interface ComponentCustomProperties {
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
